config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'class/index'
  get 'class/listado' =>  'class#listado'
  get 'class/nuevo' => 'class#nuevo'
  post 'class/crear' => 'class#crear'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/class_controller.rb
class ClassController < ApplicationController
	

  def index
  	@usuarios = User.all
  end

  def nuevo
  	@usuario = User.new
  end

  def crear
  	@usuario = User.new(params[:user].permit(:nombre, :ap, :edad, :sexo))
  	@usuario.save
  	redirect_to class_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombre, :ap, :edad, :sexo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_helper.rb
module ClassHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/class/index.html.erb
<body class="blue-grey darken-4">
<nav>
	<div class="nav-wrapper blue darken-1 full-width">
		<span class="brand-logo center">Libro de visitas</span>
	</div>
</nav>
<br>
<div class="divider"></div>
<br>
<center>
	<%= link_to 'Registrar mi visita', class_nuevo_path, class: "btn blue darken-4", style: "color:white" %>
</center>
<br>
<div class="divider"></div>
<br>
<div class="container">
	<div class="row">
		<% @usuarios.each do |u| %>
		<div class="col s4">
			<div class="card">
				<div class="card-image">
					<% if(u.edad < 21) %>
						<% if(u.sexo == "Hombre") %>
							<%= image_tag("bb.png", height: '150', width: '120', class: "")%>
						<% end %>
						<% if(u.sexo == "Mujer") %>
							<%= image_tag("bb1.png", height: '150', width: '120', class: "")%>
						<% end %>
					<% end %>
					<% if(u.edad < 26 and u.edad > 20) %>
						<% if(u.sexo == "Hombre") %>
							<%= image_tag("joven.png", height: '150', width: '120', class: "")%>
						<% end %>
						<% if(u.sexo == "Mujer") %>
							<%= image_tag("joven1.png", height: '150', width: '120', class: "")%>
						<% end %>
					<% end %>
					<% if(u.edad > 25) %>
						<% if(u.sexo == "Hombre") %>
							<%= image_tag("abuelo.png", height: '150', width: '120', class: "")%>
						<% end %>
						<% if(u.sexo == "Mujer") %>
							<%= image_tag("abuela.png", height: '150', width: '120', class: "")%>
						<% end %>
					<% end %>
				</div>
				<div class="card-content">
					<span class="card-title"><%= u.nombre %></span>
					<p><b>Nombre completo:</b></p>
					<p><%= u.nombre %> <%= u.ap %></p>
					<p><b>Edad:</b></p>
					<p><%= u.edad %></p>
					<p>Sexo: <%= u.sexo %></p>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

<footer class="page-footer blue darken-1">
	<div class="container">
		<div class="row">
			<div class="col s12 center">
				<h5 class="white-text">Creditos de la página</h5>
				<p class="grey-text text-lighten-4">Trabajo hecho en Ruby on Rails con aplicacion SaaS Heroku por:</p>
				<div class="chip">
					<%= image_tag("juan.jpg")%>
					Juan Carlos Hernández Sarmiento
				</div>
				<div class="chip">
					<%= image_tag("elia.jpg")%>
					Elia Pluma Mixcoatl
				</div>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
			<center>© 2017 Universidad Politécnica de Tlaxcala</center>
		</div>
	</div>
</footer>


</body>

app/views/class/nuevo.html.erb
<body class="blue-grey darken-4">
<nav>
	<div class="nav-wrapper blue darken-1 full-width">
		<span class="brand-logo center">Libro de visitas</span>
	</div>
</nav>
<br>
<div class="divider"></div>
<br>
<center>
	<%= link_to 'Volver al libro de visitas', class_index_path, class: "btn blue darken-4", style: "color:white" %>
</center>
<br>
<div class="divider"></div>
<br>

<div class="col s6">
	<div class="container blue lighten-5">
	<%= form_for @usuario, url: class_crear_path do |u| %>
		<div class="row">
			<div class="col s10 offset-s1"><h5><b><center>Nueva visita:</center></b></h5></div>
		</div>
		<div class="row">
			<div class="col s6 offset-s3">
				<label for="nom" class="black-text">Nombre:</label>
				<%= u.text_field :nombre, id:"nom", placeholder:"Ej: Juanito" %>
			</div>
			<div class="col s6 offset-s3">
				<label for="ap" class="black-text">Apellido(s):</label>
				<%= u.text_field :ap, id:"ap", placeholder:"Ej: Hernandez" %>
			</div>
			<div class="col s6 offset-s3">
				<label for="edad" class="black-text">Edad:</label>
				<%= u.number_field :edad, id:"edad", placeholder:"Ej: 18" %>
			</div>
			<div class="col s6 offset-s3">
				<label for="sex" class="black-text">Sexo:</label>
				<%= u.select :sexo, options_for_select([["Mujer", "Mujer"], ["Hombre", "Hombre"]]) %>
			</div>
			<div class="row">
				<div class="col s4 offset-s4">
					<center><%= u.submit "Crear", class: "btn" %></center>
				</div>
			</div>
		</div>
	<% end %>
	</div>
</div>
<br>
<script>
	$(document).ready(function() {
	    $('select').material_select();
	  });
</script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :ap %>
    <%= f.text_field :ap %>
  </div>

  <div class="field">
    <%= f.label :edad %>
    <%= f.number_field :edad %>
  </div>

  <div class="field">
    <%= f.label :sexo %>
    <%= f.text_field :sexo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ap</th>
      <th>Edad</th>
      <th>Sexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombre %></td>
        <td><%= user.ap %></td>
        <td><%= user.edad %></td>
        <td><%= user.sexo %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.nombre %>
</p>

<p>
  <strong>Ap:</strong>
  <%= @user.ap %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @user.edad %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @user.sexo %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>